CREATE TABLE MTN.Member
(
	Id INT IDENTITY(0,1),
	Email NVARCHAR(128) COLLATE Latin1_General_CI_AI NOT NULL,
	[Password] VARBINARY(255) NOT NULL,

	CONSTRAINT PK_MemberId PRIMARY KEY (Id),
	CONSTRAINT UK_MemberMail UNIQUE (Email),
);