CREATE TABLE MTN.Line
(
	Id INT IDENTITY(0,1),
	API_ID NVARCHAR(64) NOT NULL,
	[Name] NVARCHAR(255) NOT NULL,
	Color NVARCHAR(8) NOT NULL,
	Opening_time DATETIME2 NOT NULL,
	Closing_time DATETIME2 NOT NULL,
	Code NVARCHAR(32) NOT NULL
	
	CONSTRAINT PK_LineId PRIMARY KEY (Id),
	CONSTRAINT UK_LineApiId UNIQUE (API_ID),
	CONSTRAINT UK_LineName UNIQUE ([Name])
);