CREATE PROCEDURE MTN.sCreateStopArea
(
	@API_ID NVARCHAR(64),
	@Name NVARCHAR(255),
	@Lon FLOAT,
	@Lat FLOAT,
	@Id INT OUT
)
AS BEGIN
	SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
	BEGIN TRAN;
		IF EXISTS( SELECT * FROM MTN.StopArea s WHERE s.Lon = @Lon AND s.Lat = @Lat )
		BEGIN
			ROLLBACK;
			RETURN 1;
		END;
		INSERT INTO MTN.StopArea(API_ID, [Name], Lon, Lat) VALUES (@API_ID, @Name, @Lon, @Lat);
		SELECT @Id = SCOPE_IDENTITY();
	COMMIT;
	RETURN 0;
END;