create table MTN.StopArea
(
	Id INT IDENTITY(0,1),
	API_ID NVARCHAR(64) NOT NULL,
	[Name] NVARCHAR(255) NOT NULL,
	Lon FLOAT NOT NULL,
	Lat FLOAT NOT NULL,

	CONSTRAINT PK_StopAreaId PRIMARY KEY (Id),
	CONSTRAINT UK_StopAreaApiId UNIQUE (API_ID),
	CONSTRAINT UK_StopAreaName UNIQUE ([Name])
);