CREATE PROCEDURE MTN.sCreateMember
(
	@Email NVARCHAR(128),
	@Password VARBINARY(255),
	@Id INT OUT
)
AS BEGIN
	SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
	BEGIN TRAN;
		IF EXISTS( SELECT * FROM MTN.Member m WHERE m.Email = @Email )
		BEGIN
			ROLLBACK;
			RETURN 1;
		END;
		INSERT INTO MTN.Member(Email, [Password]) VALUES (@Email, @Password);
		SELECT @Id = SCOPE_IDENTITY();
	COMMIT;
	RETURN 0;
END;